<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChatroomJoinRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelJoinRepository extends EntityRepository
{
    public function findUsersInChannel($channelID)
    {

    }
}
