<?php

declare(strict_types=1);

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChatroomJoinRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatroomJoinRepository extends EntityRepository
{
}
